##############################################
# inventory/hosts.ini - GÉNÉRÉ AUTOMATIQUEMENT
# Ne pas modifier manuellement !
# Régénérer avec : python3 inventory/generate_inventory.py
##############################################

[front]
front-server ansible_host=13.38.30.115 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/medishop-key.pem

[back]
back-server ansible_host=10.0.2.208 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/medishop-key.pem ansible_ssh_common_args='-o ProxyCommand="ssh -i ~/.ssh/medishop-key.pem -o StrictHostKeyChecking=no -W %h:%p ubuntu@13.38.30.115"'

[db]
db-server ansible_host=10.0.2.103 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/medishop-key.pem ansible_ssh_common_args='-o ProxyCommand="ssh -i ~/.ssh/medishop-key.pem -o StrictHostKeyChecking=no -W %h:%p ubuntu@13.38.30.115"'

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3

[medishop:children]
front
back
db
