##############################################
# group_vars/db.yml
# Variables spécifiques à l'instance DB
##############################################

db_container_name: "medishop-db"

# Les secrets sont injectés via GitHub Secrets / variables d'env
# NE PAS mettre les vrais mots de passe ici !
mongo_root_username: "{{ lookup('env', 'MONGO_ROOT_USERNAME') | default('admin') }}"
mongo_root_password: "{{ lookup('env', 'MONGO_ROOT_PASSWORD') | default('changeme') }}"
