##############################################
# group_vars/front.yml
# Variables spécifiques à l'instance Front
##############################################

# ── Nginx ──────────────────────────────────────────────────────────────────
nginx_domain: "13.38.30.115.nip.io"  # Remplacé par le DNS dynamique
nginx_config_name: "medishop-todo"
certbot_email: "fadilops@gmail.com"  # Remplacé par un email fictif/valide

# Adresse privée du Back pour le proxy Nginx
back_private_ip: "{{ hostvars['back-server']['ansible_host'] }}"

# ── Conteneur Front ─────────────────────────────────────────────────────────
front_container_name: "medishop-front"
