##############################################
# group_vars/front.yml
# Variables spécifiques à l'instance Front
##############################################

# ── Nginx ──────────────────────────────────────────────────────────────────
nginx_domain: "todo.medishop.example.com"  # Remplacer par votre domaine
nginx_config_name: "medishop-todo"
certbot_email: "admin@medishop.example.com"  # Remplacer par votre email

# Adresse privée du Back pour le proxy Nginx
back_private_ip: "{{ hostvars['back-server']['ansible_host'] }}"

# ── Conteneur Front ─────────────────────────────────────────────────────────
front_container_name: "medishop-front"
